// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RevolvAPI.Data;

#nullable disable

namespace RevolvAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260806124539_InitialBaseline")]
    partial class InitialBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RevolvAPI.Models.ActionRecommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionText")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("AiRecommendationId")
                        .HasColumnType("int");

                    b.Property<string>("ImpactBadge")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Priority")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AiRecommendationId");

                    b.ToTable("ActionRecommendations", "revolv");
                });

            modelBuilder.Entity("RevolvAPI.Models.AiRecommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AiSummaryText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ArtikelId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<bool>("IsFullyResolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("ReturnRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("AiRecommendations", "revolv");
                });

            modelBuilder.Entity("RevolvAPI.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Companies", "revolv");
                });

            modelBuilder.Entity("RevolvAPI.Models.DescriptionProposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AiRecommendationId")
                        .HasColumnType("int");

                    b.Property<string>("CurrentText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProposedText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Ausstehend");

                    b.HasKey("Id");

                    b.HasIndex("AiRecommendationId");

                    b.ToTable("DescriptionProposals", "revolv");
                });

            modelBuilder.Entity("RevolvAPI.Models.QualityIssue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AiRecommendationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AutoAnalyzedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IssueText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Ausstehend");

                    b.HasKey("Id");

                    b.HasIndex("AiRecommendationId");

                    b.ToTable("QualityIssues", "dbo");
                });

            modelBuilder.Entity("RevolvAPI.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AbsoluteExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SessionStartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", "revolv");
                });

            modelBuilder.Entity("RevolvAPI.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles", "revolv");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "Mitarbeiter"
                        });
                });

            modelBuilder.Entity("RevolvAPI.Models.ShopSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoAnalyzeNewIssues")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<decimal>("ThresholdRed")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(25.0m);

                    b.Property<decimal>("ThresholdYellow")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(10.0m);

                    b.Property<string>("ToneOfVoice")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("Formell und sachlich");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.ToTable("ShopSettings", "revolv");
                });

            modelBuilder.Entity("RevolvAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users", "revolv");
                });

            modelBuilder.Entity("RevolvAPI.Models.Wawi.WawiItem", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ProductGroupId")
                        .HasColumnType("int");

                    b.Property<decimal>("SalesPriceNet")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Prices_SalesPriceNet");

                    b.Property<string>("Sku")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Identifiers_SKU");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.ToView("Items", "DAL");
                });

            modelBuilder.Entity("RevolvAPI.Models.Wawi.WawiItemDescription", b =>
                {
                    b.Property<int>("ArtikelId")
                        .HasColumnType("int")
                        .HasColumnName("kArtikel");

                    b.Property<int>("SpracheId")
                        .HasColumnType("int")
                        .HasColumnName("kSprache");

                    b.Property<int>("PlattformId")
                        .HasColumnType("int")
                        .HasColumnName("kPlattform");

                    b.Property<int>("ShopId")
                        .HasColumnType("int")
                        .HasColumnName("kShop");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cName");

                    b.HasKey("ArtikelId", "SpracheId", "PlattformId", "ShopId");

                    b.ToTable("tArtikelBeschreibung", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("RevolvAPI.Models.Wawi.WawiProductGroup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.ToView("ProductGroups", "DAL");
                });

            modelBuilder.Entity("RevolvAPI.Models.Wawi.WawiReturn", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ReturnDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ReturnStateId")
                        .HasColumnType("int");

                    b.Property<int?>("SalesOrderId")
                        .HasColumnType("int");

                    b.Property<int?>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.ToView("Returns", "DAL");
                });

            modelBuilder.Entity("RevolvAPI.Models.Wawi.WawiReturnLineItem", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReasonComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReturnConditionId")
                        .HasColumnType("int");

                    b.Property<int?>("ReturnId")
                        .HasColumnType("int");

                    b.Property<int?>("ReturnReasonId")
                        .HasColumnType("int");

                    b.Property<int?>("ReturnStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Sku")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SKU");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.ToView("ReturnLineItems", "DAL");
                });

            modelBuilder.Entity("RevolvAPI.Models.Wawi.WawiReturnReason", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.ToView("ReturnReasons", "DAL");
                });

            modelBuilder.Entity("RevolvAPI.Models.Wawi.WawiReturnReasonTranslation", b =>
                {
                    b.Property<int>("ReturnReasonId")
                        .HasColumnType("int");

                    b.Property<string>("LanguageId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReturnReasonId", "LanguageId");

                    b.ToTable((string)null);

                    b.ToView("ReturnReasonTranslations", "DAL");
                });

            modelBuilder.Entity("RevolvAPI.Models.Wawi.WawiReturnStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentStatusId")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("StatusType")
                        .HasColumnType("int");

                    b.Property<int?>("VisibleMode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.ToView("ReturnStatuses", "DAL");
                });

            modelBuilder.Entity("RevolvAPI.Models.Wawi.WawiSalesInvoiceLineItem", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SalesInvoiceId")
                        .HasColumnType("int");

                    b.Property<decimal>("SalesPriceNet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sku")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SKU");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.ToView("SalesInvoiceLineItems", "DAL");
                });

            modelBuilder.Entity("RevolvAPI.Models.ActionRecommendation", b =>
                {
                    b.HasOne("RevolvAPI.Models.AiRecommendation", "AiRecommendation")
                        .WithMany("ActionRecommendations")
                        .HasForeignKey("AiRecommendationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiRecommendation");
                });

            modelBuilder.Entity("RevolvAPI.Models.AiRecommendation", b =>
                {
                    b.HasOne("RevolvAPI.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RevolvAPI.Models.DescriptionProposal", b =>
                {
                    b.HasOne("RevolvAPI.Models.AiRecommendation", "AiRecommendation")
                        .WithMany("DescriptionProposals")
                        .HasForeignKey("AiRecommendationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiRecommendation");
                });

            modelBuilder.Entity("RevolvAPI.Models.QualityIssue", b =>
                {
                    b.HasOne("RevolvAPI.Models.AiRecommendation", "AiRecommendation")
                        .WithMany("QualityIssues")
                        .HasForeignKey("AiRecommendationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiRecommendation");
                });

            modelBuilder.Entity("RevolvAPI.Models.RefreshToken", b =>
                {
                    b.HasOne("RevolvAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RevolvAPI.Models.ShopSetting", b =>
                {
                    b.HasOne("RevolvAPI.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RevolvAPI.Models.User", b =>
                {
                    b.HasOne("RevolvAPI.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RevolvAPI.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RevolvAPI.Models.AiRecommendation", b =>
                {
                    b.Navigation("ActionRecommendations");

                    b.Navigation("DescriptionProposals");

                    b.Navigation("QualityIssues");
                });
#pragma warning restore 612, 618
        }
    }
}
