// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RevolvAPI.Data;

#nullable disable

namespace RevolvAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260729122651_AddRefreshTokens")]
    partial class AddRefreshTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RevolvAPI.Models.ActionRecommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AiRecommendationId")
                        .HasColumnType("int");

                    b.Property<string>("ImpactBadge")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AiRecommendationId");

                    b.ToTable("ActionRecommendations", "revolv");
                });

            modelBuilder.Entity("RevolvAPI.Models.AiRecommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AiSummaryText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<bool>("IsFullyResolved")
                        .HasColumnType("bit");

                    b.Property<decimal?>("ReturnRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("AiRecommendations", "revolv");
                });

            modelBuilder.Entity("RevolvAPI.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArticleNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Articles", "revolv");
                });

            modelBuilder.Entity("RevolvAPI.Models.DescriptionProposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AiRecommendationId")
                        .HasColumnType("int");

                    b.Property<string>("CurrentText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProposedText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AiRecommendationId");

                    b.ToTable("DescriptionProposals", "revolv");
                });

            modelBuilder.Entity("RevolvAPI.Models.QualityIssue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AiRecommendationId")
                        .HasColumnType("int");

                    b.Property<string>("IssueText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AiRecommendationId");

                    b.ToTable("QualityIssues", "dbo");
                });

            modelBuilder.Entity("RevolvAPI.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AbsoluteExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SessionStartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", "revolv");
                });

            modelBuilder.Entity("RevolvAPI.Models.ShopSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoAnalyzeNewIssues")
                        .HasColumnType("bit");

                    b.Property<decimal>("ThresholdRed")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("ThresholdYellow")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ToneOfVoice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ShopSettings", "revolv");
                });

            modelBuilder.Entity("RevolvAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", "revolv");
                });

            modelBuilder.Entity("RevolvAPI.Models.ActionRecommendation", b =>
                {
                    b.HasOne("RevolvAPI.Models.AiRecommendation", "AiRecommendation")
                        .WithMany("ActionRecommendations")
                        .HasForeignKey("AiRecommendationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiRecommendation");
                });

            modelBuilder.Entity("RevolvAPI.Models.AiRecommendation", b =>
                {
                    b.HasOne("RevolvAPI.Models.Article", "Article")
                        .WithMany("AiRecommendations")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("RevolvAPI.Models.DescriptionProposal", b =>
                {
                    b.HasOne("RevolvAPI.Models.AiRecommendation", "AiRecommendation")
                        .WithMany("DescriptionProposals")
                        .HasForeignKey("AiRecommendationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiRecommendation");
                });

            modelBuilder.Entity("RevolvAPI.Models.QualityIssue", b =>
                {
                    b.HasOne("RevolvAPI.Models.AiRecommendation", "AiRecommendation")
                        .WithMany("QualityIssues")
                        .HasForeignKey("AiRecommendationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiRecommendation");
                });

            modelBuilder.Entity("RevolvAPI.Models.RefreshToken", b =>
                {
                    b.HasOne("RevolvAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RevolvAPI.Models.AiRecommendation", b =>
                {
                    b.Navigation("ActionRecommendations");

                    b.Navigation("DescriptionProposals");

                    b.Navigation("QualityIssues");
                });

            modelBuilder.Entity("RevolvAPI.Models.Article", b =>
                {
                    b.Navigation("AiRecommendations");
                });
#pragma warning restore 612, 618
        }
    }
}
